= ISO/TC 211 Termbase programs

== Purpose

This gem is used for the creation and deployment of Geolexica,
the ISO/TC 211 Multi-Lingual Glossary Terminology database,
located at https://www.geolexica.com.

The repository for the site is located at:

* https://github.com/ISO-TC211/geolexica.com


== Install

Add this line to your Gemfile:

[source,ruby]
----
gem 'tc211-termbase'
----

And then execute:

[source,sh]
----
$ bundle
----

Or install it yourself as:

[source,sh]
----
$ gem install tc211-termbase
----


== Usage

The gem comes with the following executable:

* `tc211-termbase-xlsx2yaml`: used to extract terms from the official
  ISO/TC 211 terminology workbook, into ConceptYAML and TermYAML files.

The MLGT XLSX file can be obtained from https://committee.iso.org/sites/tc211/home/re.html


=== Using `tc211-termbase-xlsx2yaml`

Run the following command:

[source,sh]
----
$ tc211-termbase-xlsx2yaml [termbase.xlsx]
----

Where,

* the ConceptCollection YAML will be created at `[termbase.yaml]` at
  the current working directory;

* ConceptYAML files for each concept (each concept identified by a unique "`Term-ID`")
  are created under the `concepts/` directory (based on the current working directory).
  i.e. `concepts/concept-338.yaml`.


== Credits

This program is created and maintained by Ribose (the ISO/TC 211 Registration Authority)
in conjunction with the ISO/TC 211 Terminology Management Group (TMG).

